#!/bin/bash
# Setup GitHub labels for Claude Code automation

set -e

REPO="${1:-stewemetal/android-takehometemplate-multimodule}"

echo "🏷️  Setting up labels for repository: $REPO"
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed."
    echo "   Install from: https://cli.github.com/"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ Not authenticated with GitHub CLI."
    echo "   Run: gh auth login"
    exit 1
fi

echo "Creating labels..."

# Claude Code labels
gh label create "claude-code" \
    --repo "$REPO" \
    --description "Triggers Claude Code automation" \
    --color "7B68EE" \
    --force

gh label create "claude-in-progress" \
    --repo "$REPO" \
    --description "Currently being processed by Claude Code" \
    --color "FFA500" \
    --force

gh label create "automated" \
    --repo "$REPO" \
    --description "Generated by automation" \
    --color "0E8A16" \
    --force

gh label create "needs-review" \
    --repo "$REPO" \
    --description "Requires human review" \
    --color "FBCA04" \
    --force

echo "✅ Labels created successfully!"
echo ""
echo "Next steps:"
echo "1. Add ANTHROPIC_API_KEY to repository secrets"
echo "2. Enable GitHub Actions if not already enabled"
echo "3. Create a test issue with the 'claude-code' label"
echo ""
echo "For more information, see .github/CLAUDE_CODE_SETUP.md"
